Updated decoding description
Chia-Network/clvm pull request #111
Opened 2022-02-21 11:07 UTC by ChiaMineJP

The comment in serialize.py was wrong.
It told `nil` was encoded as `0xfe`.

2022-02-21 20:00 UTC, richardkiss commented on clvm/serialize.py
> +#   10xx xxxx -> 1byte is allocated for size_byte, and the value of the size is 00xx xxxx
```suggestion
#   10xx xxxx -> 1 byte is allocated for size_byte, and the value of the size is 00xx xxxx
```
(same fix for the following lines)

2022-02-21 20:01 UTC, richardkiss approved these changes
This looks good. I put forward a couple ideas to make it a little more fluid for native English speakers.

2022-02-22 01:03 UTC, ChiaMineJP commented on clvm/serialize.py
> +#   10xx xxxx -> 1byte is allocated for size_byte, and the value of the size is 00xx xxxx
Thanks! I've fixed that.

2022-02-22 03:11 UTC, richardkiss commented on clvm/serialize.py
> +# For example, if bit fields of the reading first byte are:
```suggestion
# For example, if the bit fields of reading first byte are:
```

I apologize, I made a typo in my previous suggestion. And I am a native English speaker. 😀

2022-02-22 03:13 UTC, richardkiss requested changes
I made a mistake in my previous suggestion. Sorry for making more work for you unnecessarily.

2022-02-22 10:21 UTC, ChiaMineJP commented
Sorry for making you my English teacher...

2022-02-23 00:40 UTC, richardkiss approved these changes

2022-02-23 00:40 UTC, merged